import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';


export default function Home() {

  const [isConnected, setIsConnected] = useState(false);
  const [connectButtonText, setConnectButtonText] = useState("Connect");

  async function preflightUtils() {
    const isPhantomInstalled = window.solana && window.solana.isPhantom;
    console.log("isPhantomInstalled: ", isPhantomInstalled);

    if(isPhantomInstalled) {
      window.solana.on("connect", () => {
        console.log("Connected to Phantom");
      });
    }
  }

  async function connectPhantom() {
    await window.solana.connect();
    await setIsConnected(true);
    let publicAddress = window.solana.publicKey.toString();
    let truncatedAddress = publicAddress.substring(0,3);
    truncatedAddress = truncatedAddress + "..";
    let lastFewChars = publicAddress.substr(-2);
    truncatedAddress = truncatedAddress + lastFewChars;
    setConnectButtonText(truncatedAddress);
  }



  useEffect(() => {
    async function performPreflight() {
      await preflightUtils();
    }

    performPreflight();
  },[isConnected]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Solvent Protocol - Bringing liquidity to NFTs on Solana.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/solvent-icon.ico" />
      </Head>

      <div className = {styles.navBar}>
        <div className = {styles.navColumnOne}>
          <div className = {styles.solventLogo}>
            <Image src = "/logomark_teal.png" alt="Solvent Protocol logo" width = {30} height = {40}/>
          </div>
        </div>
        <div className = {styles.navColumnTwo}>
          <button className = {styles.createButton}>Create</button>
          <button className = {styles.mintButton}>Mint</button>
        </div>
        <div className = {styles.navColumnThree}>
          <button 
            className = {styles.connectButton}
            onClick = {
              () => {
                connectPhantom();
              }
            }
          >
            {connectButtonText}
          </button>

        </div>
      </div>
      
      <div className = {styles.mainContent}>
      </div>
      

      <footer className={styles.footer}>
          Powered by{'  '}
          <span className={styles.logo}>
            <Image src="/solana-logo.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}
