import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Solvent Protocol - Bringing liquidity to NFTs on Solana.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logomark_gradient.ico" />
      </Head>

      <div className = {styles.navBar}>
      </div>
      
      <div className = {styles.mainContent}>
      </div>
      

      <footer className={styles.footer}>
          Powered by{'  '}
          <span className={styles.logo}>
            <Image src="/solana-logo.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
      </footer>
    </div>
  )
}
